// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package systemMessage

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControlpanelClient is the client API for Controlpanel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlpanelClient interface {
	NewJobService(ctx context.Context, in *NewJobRequest, opts ...grpc.CallOption) (*NewJobResponse, error)
	StartMsg(ctx context.Context, in *StartMessage, opts ...grpc.CallOption) (*StartResponse, error)
}

type controlpanelClient struct {
	cc grpc.ClientConnInterface
}

func NewControlpanelClient(cc grpc.ClientConnInterface) ControlpanelClient {
	return &controlpanelClient{cc}
}

func (c *controlpanelClient) NewJobService(ctx context.Context, in *NewJobRequest, opts ...grpc.CallOption) (*NewJobResponse, error) {
	out := new(NewJobResponse)
	err := c.cc.Invoke(ctx, "/systemMessage.controlpanel/NewJobService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlpanelClient) StartMsg(ctx context.Context, in *StartMessage, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/systemMessage.controlpanel/StartMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlpanelServer is the server API for Controlpanel service.
// All implementations must embed UnimplementedControlpanelServer
// for forward compatibility
type ControlpanelServer interface {
	NewJobService(context.Context, *NewJobRequest) (*NewJobResponse, error)
	StartMsg(context.Context, *StartMessage) (*StartResponse, error)
	mustEmbedUnimplementedControlpanelServer()
}

// UnimplementedControlpanelServer must be embedded to have forward compatible implementations.
type UnimplementedControlpanelServer struct {
}

func (UnimplementedControlpanelServer) NewJobService(context.Context, *NewJobRequest) (*NewJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewJobService not implemented")
}
func (UnimplementedControlpanelServer) StartMsg(context.Context, *StartMessage) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMsg not implemented")
}
func (UnimplementedControlpanelServer) mustEmbedUnimplementedControlpanelServer() {}

// UnsafeControlpanelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlpanelServer will
// result in compilation errors.
type UnsafeControlpanelServer interface {
	mustEmbedUnimplementedControlpanelServer()
}

func RegisterControlpanelServer(s grpc.ServiceRegistrar, srv ControlpanelServer) {
	s.RegisterService(&Controlpanel_ServiceDesc, srv)
}

func _Controlpanel_NewJobService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlpanelServer).NewJobService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systemMessage.controlpanel/NewJobService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlpanelServer).NewJobService(ctx, req.(*NewJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controlpanel_StartMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlpanelServer).StartMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systemMessage.controlpanel/StartMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlpanelServer).StartMsg(ctx, req.(*StartMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Controlpanel_ServiceDesc is the grpc.ServiceDesc for Controlpanel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controlpanel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "systemMessage.controlpanel",
	HandlerType: (*ControlpanelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewJobService",
			Handler:    _Controlpanel_NewJobService_Handler,
		},
		{
			MethodName: "StartMsg",
			Handler:    _Controlpanel_StartMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
